export const SET_IS_TAG_CIRCLE_OPEN = 'SET_IS_TAG_CIRCLE_OPEN';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const SET_SELECTED_PROJECTS = 'SET_SELECTED_PROJECTS';
export const SET_SELECTED_STUDENT = 'SET_SELECTED_STUDENT';
export const SET_SELECTED_TAG = 'SET_SELECTED_TAG';
export const SET_SELECTED_TAGS = 'SET_SELECTED_TAGS';
export const GET_STUDENT_PROJECT = 'GET_STUDENT_PROJECT';
export const GET_TAG_PROJECTS = 'GET_TAG_PROJECTS';
